using System;
using UnityEngine;
using System.Threading.Tasks;

// Example mod that demonstrates using the TransferWindowPlanner reflection wrapper.
// Drop this source into your mod's project (compile into a plugin DLL) or place
// it into PluginFiles/ExampleTWPClient/ in the repo for reference.

[KSPAddon(KSPAddon.Startup.Flight, false)]
public class ExampleTWPClient : MonoBehaviour
{
    async void Start()
    {
        Debug.Log("[ExampleTWPClient] Starting and waiting for TWP API...");

        // Wait up to ~15 seconds for TWP to become available
        int tries = 30;
        while (tries-- > 0 && !TWP_ReflectionWrapper.IsAvailable())
        {
            await Task.Delay(500);
        }

        if (!TWP_ReflectionWrapper.IsAvailable())
        {
            Debug.Log("[ExampleTWPClient] TransferWindowPlanner API not found. Make sure TransferWindowPlanner is installed and enabled.");
            return;
        }

        try
        {
            // Build a request (Kerbin -> Mun example). Times are in UT seconds.
            var req = new TWP_ReflectionWrapper.TransferRequestDTO
            {
                OriginBodyName = "Kerbin",
                DestinationBodyName = "Mun",
                DepartureUT = Planetarium.GetUniversalTime() + 86400.0, // ~1 day from now
                TimeOfFlightUT = 3 * 24 * 3600.0, // ~3 days
                InitialOrbitAltitude = 100000.0, // meters
                InitialOrbitInclinationRad = 0.0, // radians
                FinalOrbitAltitude = 100000.0 // meters
            };

            Debug.Log("[ExampleTWPClient] Requesting transfer calculation (async)...");
            var res = await TWP_ReflectionWrapper.CalculateTransferAsync(req);

            if (!res.Success)
            {
                Debug.LogError("[ExampleTWPClient] Transfer calculation failed: " + res.ErrorMessage);
                return;
            }

            Debug.LogFormat("[ExampleTWPClient] Transfer result: Δv={0:F2} m/s, DepartureUT={1}, TOF={2}", res.TotalDeltaV, res.DepartureUT, res.TimeOfFlightUT);

            // Build an alarm spec and try to register it with KAC via TWP.
            var alarm = TWP_ReflectionWrapper.BuildKACAlarmForTransfer(res, leadSeconds: 600, alarmName: "Example TWP Burn", notes: "Generated by ExampleTWPClient");
            bool registered = false;
            if (alarm != null)
            {
                registered = TWP_ReflectionWrapper.TryRegisterKACAlarm(alarm);
            }
            Debug.LogFormat("[ExampleTWPClient] KAC registration attempted: {0}", registered);
        }
        catch (Exception ex)
        {
            Debug.LogError("[ExampleTWPClient] Exception: " + ex);
        }
    }
}
